#!/usr/bin/env bash
# -*- coding: utf-8; tab-width: 4; c-basic-offset: 4; indent-tabs-mode: nil -*-

# A script to source the environment to build an embedded Linux system with
# OpenEmbedded/Poky from scratch
# Copyright (C) 2014  Thomas Perrot <thomas.perrot@tupi.fr>

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA

umask 022

export TEMPLATECONF="meta-tprrt/meta-exiguous/conf"

CWD=$(pwd)
export PATH="${CWD}/exiguous/meta-tprrt/scripts:${PATH}"

source ./exiguous/oe-init-build-env $@
